---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: baseapplication
namespace: sampleapp

resources:
  - ../../baseapplication

nameSuffix: -dev
namePrefix: dev-

## Adding Labels to all resources.
commonLabels:
  app: dev
  env: dev

## Adding Lables to configmap and secrets
generatorOptions:
  labels:
    env: dev


# In-case we want to modify only replicas we can use below code within
# replicas block instead of patch
# replicas:
#   - name: dev-sampleapp-deployment-dev
#     count: 3


patchesStrategicMerge:
  - dev-deployment-patch.yaml


secretGenerator:
  - name: registry-secret
    type: docker-registry
    literals:
      - docker-username="vasudevdchavan"
      - docker-password="kubernetes@1234"
      - docker-server="docker.io"
      - docker-email="vasudevdchavan@gmail.com"
    options:
      disableNameSuffixHash: true