---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-postgres
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
      tier: postgres
  template:
    metadata:
      labels:
        app: example-app
        tier: postgres
    spec:
      containers:
        - image: postgres
          name: postgres
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: example-postgres-secrets
                  key: root_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-stateful-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-stateful-data
          persistentVolumeClaim:
            claimName: example-postgres


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-postgres
  labels:
    app: example-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: example-postgres-secrets
type: Opaque
data:
  # echo "password" | base64
  root_password: cGFzc3dvcmQK

---

apiVersion: v1
kind: Service
metadata:
  name: example-postgres
  labels:
    app: example-app
spec:
  ports:
    - port: 5432
  type: LoadBalancer
  selector:
    app: example-app
    tier: postgres

---

## Referance from https://github.com/ryderdamen/postgres_in_kubernetes/tree/master