apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment
  namespace: sampleapp
  labels:
    app: sampleapp
spec:
  template:
    spec:
      containers:
      - name: sampleapp
        image: docker.io/vasudevdchavan/addition-operator:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      imagePullSecrets:
      - name: prod-registry-secret-prod