---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: baseapplication
namespace: sampleapp
resources:
  - baseapplication/01-namespace.yaml
  - baseapplication/02-deployment.yaml

